/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MainRouteImport } from './routes/_main'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as MainGraphRouteImport } from './routes/_main/graph'
import { Route as MainChar123IdChar125RouteImport } from './routes/_main/{-$id}'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as SettingsAgentRouteImport } from './routes/settings/agent'
import { Route as SettingsApiKeyRouteImport } from './routes/settings/api-key'
import { Route as SettingsModelRouteImport } from './routes/settings/model'
import { Route as SettingsProviderRouteImport } from './routes/settings/provider'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const MainGraphRoute = MainGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => MainRoute,
} as any)
const MainChar123IdChar125Route = MainChar123IdChar125RouteImport.update({
  id: '/{-$id}',
  path: '/{-$id}',
  getParentRoute: () => MainRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAgentRoute = SettingsAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeyRoute = SettingsApiKeyRouteImport.update({
  id: '/api-key',
  path: '/api-key',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelRoute = SettingsModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProviderRoute = SettingsProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/graph': typeof MainGraphRoute
  '/{-$id}': typeof MainChar123IdChar125Route
  '/api/chat': typeof ApiChatRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/api-key': typeof SettingsApiKeyRoute
  '/settings/model': typeof SettingsModelRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof MainRouteWithChildren
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/graph': typeof MainGraphRoute
  '/{-$id}': typeof MainChar123IdChar125Route
  '/api/chat': typeof ApiChatRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/api-key': typeof SettingsApiKeyRoute
  '/settings/model': typeof SettingsModelRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_main/graph': typeof MainGraphRoute
  '/_main/{-$id}': typeof MainChar123IdChar125Route
  '/api/chat': typeof ApiChatRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/api-key': typeof SettingsApiKeyRoute
  '/settings/model': typeof SettingsModelRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/graph'
    | '/{-$id}'
    | '/api/chat'
    | '/settings/about'
    | '/settings/agent'
    | '/settings/api-key'
    | '/settings/model'
    | '/settings/provider'
    | '/settings/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/graph'
    | '/{-$id}'
    | '/api/chat'
    | '/settings/about'
    | '/settings/agent'
    | '/settings/api-key'
    | '/settings/model'
    | '/settings/provider'
    | '/settings'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/settings'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_main/graph'
    | '/_main/{-$id}'
    | '/api/chat'
    | '/settings/about'
    | '/settings/agent'
    | '/settings/api-key'
    | '/settings/model'
    | '/settings/provider'
    | '/settings/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/graph': {
      id: '/_main/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof MainGraphRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/{-$id}': {
      id: '/_main/{-$id}'
      path: '/{-$id}'
      fullPath: '/{-$id}'
      preLoaderRoute: typeof MainChar123IdChar125RouteImport
      parentRoute: typeof MainRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/agent': {
      id: '/settings/agent'
      path: '/agent'
      fullPath: '/settings/agent'
      preLoaderRoute: typeof SettingsAgentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-key': {
      id: '/settings/api-key'
      path: '/api-key'
      fullPath: '/settings/api-key'
      preLoaderRoute: typeof SettingsApiKeyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/model': {
      id: '/settings/model'
      path: '/model'
      fullPath: '/settings/model'
      preLoaderRoute: typeof SettingsModelRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/provider': {
      id: '/settings/provider'
      path: '/provider'
      fullPath: '/settings/provider'
      preLoaderRoute: typeof SettingsProviderRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainGraphRoute: typeof MainGraphRoute
  MainChar123IdChar125Route: typeof MainChar123IdChar125Route
}

const MainRouteChildren: MainRouteChildren = {
  MainGraphRoute: MainGraphRoute,
  MainChar123IdChar125Route: MainChar123IdChar125Route,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAgentRoute: typeof SettingsAgentRoute
  SettingsApiKeyRoute: typeof SettingsApiKeyRoute
  SettingsModelRoute: typeof SettingsModelRoute
  SettingsProviderRoute: typeof SettingsProviderRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAgentRoute: SettingsAgentRoute,
  SettingsApiKeyRoute: SettingsApiKeyRoute,
  SettingsModelRoute: SettingsModelRoute,
  SettingsProviderRoute: SettingsProviderRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
