/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as MainGraphRouteImport } from './routes/_main/graph'
import { Route as MainChar123IdChar125RouteImport } from './routes/_main/{-$id}'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/_auth/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MainGraphRoute = MainGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => MainRoute,
} as any)
const MainChar123IdChar125Route = MainChar123IdChar125RouteImport.update({
  id: '/{-$id}',
  path: '/{-$id}',
  getParentRoute: () => MainRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainRouteWithChildren
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/graph': typeof MainGraphRoute
  '/{-$id}': typeof MainChar123IdChar125Route
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof MainRouteWithChildren
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/graph': typeof MainGraphRoute
  '/{-$id}': typeof MainChar123IdChar125Route
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_main/graph': typeof MainGraphRoute
  '/_main/{-$id}': typeof MainChar123IdChar125Route
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin' | '/signup' | '/graph' | '/{-$id}' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/signup' | '/graph' | '/{-$id}' | '/api/auth/$'
  id:
    | '__root__'
    | '/_main'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_main/graph'
    | '/_main/{-$id}'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/graph': {
      id: '/_main/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof MainGraphRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/{-$id}': {
      id: '/_main/{-$id}'
      path: '/{-$id}'
      fullPath: '/{-$id}'
      preLoaderRoute: typeof MainChar123IdChar125RouteImport
      parentRoute: typeof MainRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainRouteChildren {
  MainGraphRoute: typeof MainGraphRoute
  MainChar123IdChar125Route: typeof MainChar123IdChar125Route
}

const MainRouteChildren: MainRouteChildren = {
  MainGraphRoute: MainGraphRoute,
  MainChar123IdChar125Route: MainChar123IdChar125Route,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
